[project]
name = "ai-engineer-os"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Joseph Ssemuli", email = "2024BCS152@std.must.ac.ug" }
]
requires-python = ">=3.13"
dependencies = [
    "black>=26.5.1",
    "pre-commit>=4.6.1",
    "pytest>=9.1.1",
    "ruff>=0.16.1",
]

[project.scripts]
ai-engineer-os = "ai_engineer_os:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
